---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: robertdebock/ubuntu
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: "/usr/sbin/init"
    capabilities:
      - SYS_ADMIN
    pre_build_image: true
    privileged: True
provisioner:
  name: ansible
  env:
    ANSIBLE_VAULT_TOKEN: $VAULT_TOKEN
    ANSIBLE_VAULT_ADDR: $VAULT_ADDR
verifier:
  name: ansible
scenario:
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
