---
  - name: Install Required Packages
    include_role:
      name: provision_packages
    vars:
      packages_to_install:
        - discount

      services: []

  - name: Copy the Apache configuration file
    ansible.builtin.copy:
      src: files/etc/
      dest: /etc
      owner: root
      group: root
    notify: Restart apache2

  - name: Enable external filter module
    ansible.builtin.shell:
      cmd: "a2enmod ext_filter"

  - name: Enable markdown
    ansible.builtin.shell:
      cmd: "a2enconf markdown"
    notify: Restart apache2
