---

all:
  hosts:
# For local development and testing
    hub.dis.com:

      dnsmasq_proxy:                true
      dnsmasq_network_interface:    enp0s5
# 10.10.1.50 is nbamdemo
      dnsmasq_network_dhcp:         "10.10.1.50,proxy,255.255.255.0"

      external_network_gateway:     10.10.1.1
      internal_network_address:     10.10.1.45

      ubuntu_iso:                   http://ubuntu-vm.dis.com/ubuntu-{{ ubuntu_version }}-live-server-amd64.iso
      userdata_network_interface:   enp88s0
