---
# packages_to_install:
# A list of packages to install
#
# For example:
#     packages_to_install:
#       - apcupsd
#       - argp-standalone
#       - asciidoc
#       - aspell


  - debug: var=packages_to_install

  - name: Install packages
    ansible.builtin.package:
      name: "{{ packages_to_install | list }}"
      state: latest

  - name: Reload systemd
    ansible.builtin.systemd:
      daemon_reload: true

  - name: Make sure services are started
    ansible.builtin.systemd:
      name: "{{ item }}"
      enabled: yes
      masked: no
      state: started
    with_items: "{{ services }}"
    when: services is defined and services | length > 0
