{
 "title": "Link Quality",
 "description": "Sample Dashboard showing link quality",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "NBAM Site Map",
   "type": "geomap",
   "description": "Shows the location of North Bay Mesh Nodes",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_aredn_info{lat != \"0\", lon != \"0\"} == on(instance) group_left(channel, firmware) node_aredn_meshrf",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Link Quality",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_lqm_tracker_quality {type=\"RF\"}",
     "legendFormat": "{{hostname}} to {{instance}}"
    }
   ]
  },
  {
   "title": "Neighbor Quality",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(node_olsr_link_neighbor_link_quality {device=\"wlan0\"}, \"short_hostname\", \"$1\", \"instance\", \"(.*):.*\") * on(instance, remote_ip) group_left(hostname)  label_replace(node_lqm_tracker_ping_quality{type=\"RF\"}, \"remote_ip\", \"$1\",\"ip\",\"(.*)\")",
     "legendFormat": "{{short_hostname}} to {{hostname}}"
    }
   ]
  }
 ]
}