{
 "title": "North Bay Mesh Overview",
 "description": "Sample Dashboard showing link quality",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "node_name", "label": "Site", "query": { "query": "query_result(node_aredn_info)" } }
  ]
 },
 "panels": [
  {
   "title": "NBAM Site Map",
   "type": "geomap",
   "description": "Shows the location of North Bay Mesh Nodes",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_aredn_info{lat!=\"\", lon!=\"\", job=\"nbam-site-survey\"} == on(instance,job) group_left(channel) node_aredn_meshrf",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Link Quality",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_lqm_tracker_quality {type=\"RF\"}",
     "legendFormat": "{{hostname}} to {{instance}}"
    }
   ]
  },
  {
   "title": "Neighbor Quality",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(node_olsr_link_neighbor_link_quality {device=\"wlan0\"}, \"short_hostname\", \"$1\", \"instance\", \"(.*):.*\") * on(instance, remote_ip) group_left(hostname)  label_replace(node_lqm_tracker_ping_quality{type=\"RF\"}, \"remote_ip\", \"$1\",\"ip\",\"(.*)\")",
     "legendFormat": "{{short_hostname}} to {{hostname}}"
    }
   ]
  },
  { "title": "Site Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "$node_name",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
   "repeat": "node_name",
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~\"(?i:($node_name)):80\", device=\"eth0\"}[15m]) * 8",
     "legendFormat": "TX"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~\"(?i:($node_name)):80\", device=\"eth0\"}[15m]) * 8",
     "legendFormat": "RX"
    }
   ]
  }
 ]
}