{
 "title": "RF Max Bit Rates",
 "description": "Displays the bit rate between RF nodes.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "query_result(node_lqm_tracker_tx_bitrate{type=\"RF\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Transmit Bitrate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "node_lqm_tracker_tx_bitrate{instance=\"$node_name\", type=\"RF\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Receive Bitrate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "node_lqm_tracker_rx_bitrate{instance=\"$node_name\", type=\"RF\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Signal Quality",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_lqm_tracker_quality{instance=\"$node_name\", type=\"RF\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "SNR",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_lqm_tracker_avg_snr{instance=\"$node_name\", type=\"RF\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Link SNR",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_lqm_tracker_rev_snr{instance=\"$node_name\", type=\"RF\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  }
 ]
}