{
 "title": "Site Traffic Detail",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "node_name", "label": "Node Name", "query": { "query": "query_result(node_aredn_info)" } },
   {
    "name": "peer",
    "label": "Peer",
    "query": {
     "query": "query_result(node_lqm_tracker_tx_bitrate{type=\"RF\",instance=\"$node_name:80\"})"
    }
   },
   {
    "name": "node_ip",
    "label": "Node IP Address",
    "query": {
     "query": "query_result(node_olsr_link_link_quality{device=\"wlan0\",instance=~\"(?i:($node_name)):80\"})"
    }
   },
   {
    "name": "peer_ip",
    "label": "Node IP Address",
    "query": {
     "query": "query_result(node_olsr_link_link_quality{device=\"wlan0\",instance=~\"(?i:($peer)):80\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Traffic Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~\"(?i:($node_name)):80|(?i:($peer)):80\", device=\"wlan0\"}[15m]) * 8",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$node_name to $peer",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_lqm_tracker_tx_quality{instance=~\"(?i:($node_name)):80\", ip=\"$peer_ip\"} / 100",
     "legendFormat": "LQ"
    },
    {
     "expr": "node_olsr_link_neighbor_link_quality{local_ip=\"$node_ip\",remote_ip=\"$peer_ip\"}",
     "legendFormat": "NLQ"
    },
    {
     "expr": "node_lqm_tracker_quality{instance=~\"(?i:($node_name)):80\", ip=\"$peer_ip\"} / 100",
     "legendFormat": "Neighbor Quality"
    }
   ]
  },
  {
   "title": "$peer to $node_name",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_lqm_tracker_tx_quality{instance=~\"(?i:($peer)):80\", ip=\"$node_ip\"} / 100",
     "legendFormat": "LQ"
    },
    {
     "expr": "node_olsr_link_neighbor_link_quality{local_ip=\"$peer_ip\",remote_ip=\"$node_ip\"}",
     "legendFormat": "NLQ"
    },
    {
     "expr": "node_lqm_tracker_quality{instance=~\"(?i:($peer)):80\", ip=\"$node_ip\"} / 100",
     "legendFormat": "Neighbor Quality"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "node_lqm_tracker_quality{instance=~\"(?i:($node_name)):80\", hostname=~\"(?i:($peer))\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_olsr_link_link_quality{device=\"wlan0\",instance=~\"(?i:($node_name)):80\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}