version: 0.1
auth:
  htpasswd:
    realm: registry-realm
    path: /auth/htpasswd
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Methods: [HEAD, GET, OPTIONS, DELETE]
    Access-Control-Allow-Headers: [Authorization, Accept, Cache-Control]
    Access-Control-Max-Age: [1728000]
    Access-Control-Allow-Credentials: [true]
    Access-Control-Expose-Headers: [Docker-Content-Digest]
# tls:
#   certificate: /certs/dis.crt
#   key: /certs/private/dis.com.key
#   clientcas:
#     - /certs/cacert.pem
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
