---

  - name: Restart apache2
    ansible.builtin.service:
      name: apache2
      state: restarted
    become: true

  - name: Restart dnsmasq
    ansible.builtin.service:
      name: dnsmasq
      state: restarted
    become: true

  - name: Restart syslogd
    ansible.builtin.service:
      name: syslogd
      state: restarted
    become: true

  - name: Unmount the ISO
    ansible.posix.mount:
      path: /mnt
      state: absent
    become: true

