---

  - name: Restart apache2
    ansible.builtin.service:
      name: apache2
      state: restarted

  - name: Restart dnsmasq
    ansible.builtin.service:
      name: dnsmasq
      state: restarted

  - name: Restart syslogd
    ansible.builtin.service:
      name: syslogd
      state: restarted

  - name: Unmount the ISO
    ansible.posix.mount:
      path: /mnt
      state: absent

