---

  - name: Install Vault. This is only in snap and not apt.
    community.general.snap:
      name:
        - vault

  - name: "Check if the vault group exists"
    ansible.builtin.getent:
      database: group
      key:      "vault"
      fail_key: false
    register: getent_output

  - debug: var=getent_output

  - name: Set whether not the vault group exists
    ansible.builtin.set_fact:
      vault_group_exists: "{{ ansible_facts.getent_group['vault'] is not none }}"

  - name: Initialize aredn_in_vault_group fact
    ansible.builtin.set_fact:
      aredn_in_vault_group:   false

  - name: Is aredn user in vault group?
    ansible.builtin.set_fact:
      aredn_in_vault_group: "{{ ansible_facts.getent_group['vault']['aredn'] is not none }}"
    when:   vault_group_exists

  - name: Add user vault group if needed
    ansible.builtin.group:
      name:     "vault"
      state:    present
    when:       not vault_group_exists

  - name: "Check if the vault user exists"
    ansible.builtin.getent:
      database: passwd
      key:     "vault"
      fail_key: false

  - name: Set whether not the user exists
    ansible.builtin.set_fact:
      vault_user_exists: "{{ ansible_facts.getent_group['vault'] is not none }}"

  - name: Add user vault
    ansible.builtin.user:
      name:       "vault"
      comment:    "Hashicorp Vault Account"
      groups:     "vault"
      system:     true
      shell:      "/bin/false"
      createhome: "false"
    when:         not vault_user_exists

  - name: Make sure the aredn user is in the vault group
    ansible.builtin.user:
      name:       "aredn"
      groups:     "vault"
      state:      present
      append:     yes
    when:         not aredn_in_vault_group

  - name: Make sure vault is running
    community.docker.docker_container_info:
      name: vault
    register: vault_status

  - set_fact:
      vault_running: "{{ vault_status.exists and vault_status.container.State.Running }}"

  - name: Stop vault if it is running
    community.docker.docker_container:
      state: absent
      name:  vault
    when: vault_running == true

  - name: Fetch or update the container
    community.docker.docker_image_pull:
      docker_host:  "unix:///run/docker.sock"
      name:         hashicorp/vault

  - name: Make sure /vault and friends exist
    ansible.builtin.file:
      path: "{{ item }}"
      owner: vault
      group: vault
      state: directory
      mode: u=rwx,g=rx
    with_items:
      - /vault/config
      - /vault/data
      - /vault/file
      - /vault/logs
      - /vault/policies

  - name: Copy the configuration and policy files
    ansible.builtin.copy:
      src:          files/vault/
      dest:         /vault
      owner:        vault
      group:        vault

  - name: Start the vault container
    community.docker.docker_container:
      capabilities:
        - ipc_lock
      command:          server
      image:            hashicorp/vault
      name:             vault
      ports:
        - "8200:8200"
        - "8201:8201"
      restart_policy:   "unless-stopped"
      state:            started
      volumes:
        - /vault:/vault
        - /vault/file:/vault/file
    register: vault_status

  - name: Wait for the container to be healty
    community.docker.docker_container_info:
      name:     vault
    until:      vault_status.container.State.Running
    register:   vault_status
    retries:    15
    delay:      10

  - name: See if the vault has been initialized
    ansible.builtin.shell: |
      vault status -address=http://127.0.0.1:8200
    register: vault_status
    failed_when: 
      - vault_status.rc == 1
      - vault_status.rc > 2

  - name: Vault Status Variable
    debug:
      var: vault_status

  - name: Set vault_initialized fact
    ansible.builtin.set_fact:
      vault_initialized:    '{{ vault_status.stdout | regex_search(".*Initialized\s+(true|false)","\1") | first | bool }}'
      vault_sealed:         '{{ vault_status.stdout | regex_search(".*Sealed\s+(true|false)","\1") | first | bool }}'

  - name: Initialize Vault if needed
    ansible.builtin.shell: |
      vault operator init -address=http://127.0.0.1:8200 
    register: vault_seal_keys
    when: not vault_initialized

  - name: Fetch Seal Keys
    ansible.builtin.set_fact:
      vault_key1:   '{{ vault_seal_keys.stdout | regex_search(".*Unseal Key 1:\s+(.*)","\1") | first }}'
      vault_key2:   '{{ vault_seal_keys.stdout | regex_search(".*Unseal Key 2:\s+(.*)","\1") | first }}'
      vault_key3:   '{{ vault_seal_keys.stdout | regex_search(".*Unseal Key 3:\s+(.*)","\1") | first }}'
      vault_token:  '{{ vault_seal_keys.stdout | regex_search(".*Token:\s+(.*)","\1") | first }}'
    when: not vault_initialized

  - name: Save Keys
    ansible.builtin.copy:
      dest:     '/vault_keys'
      content:  |
        {
          "key1":   "{{ vault_key1 }}",
          "key2":   "{{ vault_key2 }}",
          "key3":   "{{ vault_key3 }}",
          "token":  "{{ vault_token }}"
        }
      owner: root
      group: vault
      mode:  0640
    when: not vault_initialized

  - name: Unseal the vault if needed
    ansible.builtin.include_tasks: unseal_vault.yml
    when: vault_sealed

  - name: Create concourse policy
    ansible.builtin.shell: |
        export VAULT_ADDR="http://{{ inventory_hostname }}:8200"
        export VAULT_TOKEN="{{ vault_token }}"
        cat /vault/policies/concourse.hcl | vault policy write concourse -

  - debug:
      msg: |
            If this is a new vault and you are installing Concourse, you will
            need to generate a new token for it. Do this with:
              vault token create -format=json -policy="concourse" | jq -r ".auth.client_token"
            Make sure to update the inventory with the new token prior to
            deploying Concourse.
