---

  - name: Restart apache2
    ansible.builtin.service:
      name: apache2
      state: restarted

  - name: Restart syslogd
    ansible.builtin.service:
      name: syslogd
      state: restarted
