{
 "title": "Smorgasboard3",
 "description": "Test panel to see all of the metrics offered",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "node_olsr_link_link_quality",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_olsr_link_link_quality", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "node_olsr_link_loss_hello_interval",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_olsr_link_loss_hello_interval",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "node_olsr_link_loss_multiplier",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_olsr_link_loss_multiplier", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "node_olsr_link_loss_time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_olsr_link_loss_time", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "node_olsr_link_neighbor_link_quality",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_olsr_link_neighbor_link_quality",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "node_olsr_link_seqno",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_olsr_link_seqno", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "node_olsr_link_symmetry_time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_olsr_link_symmetry_time", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "node_olsr_link_validity_time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_olsr_link_validity_time", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "node_olsr_link_vtime",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_olsr_link_vtime", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}