{
 "title": "Smorgasboard1",
 "description": "Test panel to see all of the metrics offered",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "node_uname_info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "node_uname_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "node_lqm_tracker_distance",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_lqm_tracker_distance", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "lqm_tracker_avg_snr",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_lqm_tracker_avg_snr", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "node_lqm_tracker_exposed",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_lqm_tracker_exposed", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "node_lqm_tracker_last_tx",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_lqm_tracker_last_tx", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "node_lqm_tracker_last_tx_total",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_lqm_tracker_last_tx_total", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "node_lqm_tracker_lat",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_lqm_tracker_lat", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "node_lqm_tracker_lon",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_lqm_tracker_lon", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "node_lqm_tracker_ping_quality",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_lqm_tracker_ping_quality", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "node_lqm_tracker_ping_success_time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_lqm_tracker_ping_success_time",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "node_lqm_tracker_quality",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_lqm_tracker_quality", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "node_lqm_tracker_quality",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_lqm_tracker_quality", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "node_lqm_tracker_quality",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_lqm_tracker_quality", "legendFormat": "{{hostname}}" }
   ]
  }
 ]
}