{
 "title": "Smorgasboard2",
 "description": "Test panel to see all of the metrics offered",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "node_lqm_tracker_rev_snr",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_lqm_tracker_rev_snr", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "node_lqm_tracker_routable",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_lqm_tracker_routable", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "node_lqm_tracker_rx_bitrate",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_lqm_tracker_rx_bitrate", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "node_lqm_tracker_tx_bitrate",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_lqm_tracker_tx_bitrate", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "node_lqm_tracker_tx_quality",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_lqm_tracker_tx_quality", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "node_lqm_tracker_user_allow",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_lqm_tracker_user_allow", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "node_olsr_link_asymmetry_time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_olsr_link_asymmetry_time", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "node_olsr_link_hello_time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_olsr_link_hello_time", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "node_olsr_link_hysteresis",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_olsr_link_hysteresis", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "node_olsr_link_last_hello_time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_olsr_link_last_hello_time", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "node_olsr_link_link_cost",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_olsr_link_link_cost", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "node_lqm_tracker_quality",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_lqm_tracker_quality", "legendFormat": "{{hostname}}" }
   ]
  }
 ]
}